project:
  type: website

execute:
  freeze: auto
  
website:
  title: "Patricio Said"
  navbar:
    left:
      - href: index.qmd
        text: Home2
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

